.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. pavcoin_qt test_pavcoin_qt
clean: FORCE
	$(MAKE) -C .. pavcoin_qt_clean test_pavcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_pavcoin_qt_check
pavcoin-qt pavcoin-qt.exe: FORCE
	 $(MAKE) -C .. pavcoin_qt
